### PR TITLE
separate linux and windows run instructions

### PR DESCRIPTION
**Pull request by connerk**
sudo does not work in PowerShell. 😄

### CODE REVIEW

**Comment by pcunning** [comment]
this is included in #31

**Comment by pcunning** [comment]
this is included in #31

**Comment by pygmyhulk** [comment]
Hey guys its Alex K from a long time ago, I dont know my username or
password for github, can you remove me from the thread or mute it for me?

**Comment by pcunning** [comment]
@pygmyhulk looks like we can't remove you from our end. You can do a forgot password and unfollow the repo. https://github.com/rogue-hack-lab/rogue-hack-lab.github.io/watchers

**Pull request closed without merging**
